### ISSUE TITLE
Hybrid Mode seems like not working

### ISSUE THREAD

**Issue by madTeddy** [gabordemooij/redbean#762]
Trying to use hybrid mode, but nothing is going on and no errors.
**Code:**
```php
require_once 'rb-mysql.php';

R::setup( 'mysql:host=localhost;dbname=test', 'root', '' );
R::useFeatureSet('novice/latest');
R::setAllowHybridMode(true);
R::freeze(true);

$table = R::dispense($tab); //table is not exists in db
$table->player = $player_id;
$table->value = $value;

R::store($table, true);
```
**Log:**
```sql
SET NAMES utf8mb4
SELECT `tab26122019`.*  FROM `tab26122019`  WHERE player = 6 LIMIT 1   -- keep-cache
```
Just one MySQL request and that's all.
If I don't allow the **HybridMode**, then just an error occurs (obviously).

**Comment by gabordemooij** [comment]
You are using R::store() but the query seems to be a select query. I did find another issue though:
- the 2nd parameter is not checked for some reason
- the frozen state is not correctly changed back
Will fix these immediately.

**Comment by gabordemooij** [comment]
The issues that I did found should have been fixed now.
https://github.com/gabordemooij/redbean/commit/58d366ac135cf14c7b952cda075a7723dfb425a7

**Comment by madTeddy** [comment]
Thank you

**Comment by madTeddy** [comment]
**I'm sorry**, but now in freeze mode without hybrid mode, no errors occurs when table not exists...
Same one **SELECT** request and that's all _(I just testing, because hybrid mode still not working (or I using it wrong) and freezing is not working correctly from new fixes)_.
Code which **must generate an exception**, when table not exists _(like it said in comment to the store function)_:
```php
require_once 'rb-mysql.php';

R::setup( 'mysql:host=localhost;dbname=test', 'root', '' );
R::useFeatureSet('novice/latest');
R::freeze(true);

$table = R::dispense($tab); //table is not exists in db
$table->player = $player_id;
$table->value = $value;

R::store($table);
```
I think it's because of wrong _if statement_ in **rb-mysql.php** (maybe):
```php
if ( !self::$allowHybridMode || !$unfreezeIfNeeded ) throw $exception;
```

**Comment by madTeddy** [comment]
And yep, problem was with mine code. I'm did the **fineOne** method in try block, and did a search in a nonexistent table. But result was always **isset = TRUE**, because it was filled with previous data for some reason...
